# Generated by Django 4.1 on 2022-09-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_productsstore_store_alter_tagsstore_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='N/A', max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='ref',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
